[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/vulcand/oxy"

[prune]
  go-tests = true
  unused-packages = true
